title: Seenivasan Hariharan
email: quasiquantumnl@gmail.com
description: >-
  Independent Researcher and Consultant specialising in Quantum Computing for Chemistry.
  Developing quantum algorithms and computational methods for molecular simulation and materials discovery.
baseurl: ""
url: "https://seenivasan.github.io"
github_username: seenivasanh

# Post URL format: /posts/2026/my-post-title/
permalink: /posts/:year/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
